### ISSUE TITLE
I'm getting Segmentation fault: 11 error when login

### ISSUE THREAD

**Issue by Ivluengo** [lastpass/lastpass-cli#550]
Hi everyone! I just tried to use the Alfred's workflow of LastPass and it is using LastPass cli. I'm having this error when I try to login: 

`ERROR: LastPass CLI[Run Script] 2465:2767: execution error: /bin/bash: line 1: 23269 Segmentation fault: 11  /usr/local/bin/lpass login --trust "myemail" (139)`

Then I tried to login via Terminal and I'm getting 

`Segmentation fault: 11`

I have searched in all the issues and I don't find any solution. I tried reinstalling the cli but still...
I'm using in it on a macOS Sierra version 10.13.6

Thanks a lot!

**Comment by optimizasean** [comment]
Same here.  LastPass please fix this soon.  I rely on this and am currently unable to get my passwords on to the devices I need them on.  Lucky me I am logged on so until my trust expires I will still have access to the passwords already on my device, unfortunately that will not last forever and I need my new passwords for certain accounts.

**Comment by swathisainadh** [comment]
Hi,
I have the same issue, kindly fix this at the earliest.

**Comment by alexkuc** [comment]
When you tried [this](https://github.com/lastpass/lastpass-cli/issues/427#issuecomment-427329292) workaround? I am on `10.13.6`, had exactly the same issue and linked comment helped me fix the issue.

**Comment by swathisainadh** [comment]
I upgraded to Catalina and this issue has been resolved now. Somehow doesn't work on High Sierra.

**Comment by auto9suns** [comment]
I am on High Sierra. doesn't work for me as well. seem an OpenSSL issue they mentioned before

**Comment by RHamers** [comment]
same here, High Sierra too.

**Comment by optimizasean** [comment]
I am also on High Sierra.

**Comment by abaines** [comment]
I'm pretty sure I'm still encountering this issue in 2026, with the machine:
```
Chip Apple M4 Pro
macOS Sequoia 15.7.3
```
Seems related to https://github.com/lastpass/lastpass-cli/issues/427 issue.
Hoping for the official LastPass recommended steps to fix this.

Thanks! 🤗
